---
- name: Update Docker Version
  hosts: your_docker_hosts
  become: yes  # Run tasks with sudo

  tasks:
    - name: Remove old Docker packages
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker-ce
        - docker-ce-cli
        - containerd.io
      when: ansible_pkg_mgr == 'apt'  # Adjust for other package managers

    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_pkg_mgr == 'apt'  # Adjust for other package managers

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_pkg_mgr == 'apt'  # Adjust for other package managers

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
      when: ansible_pkg_mgr == 'apt'  # Adjust for other package managers

    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'  # Adjust for other package managers

    - name: Install the desired Docker version
      apt:
        name: "docker-ce={{ docker_version }} docker-ce-cli={{ docker_version }} containerd.io"
        state: present
      when: ansible_pkg_mgr == 'apt'  # Adjust for other package managers
      vars:
        docker_version: "your_desired_docker_version"

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
