---
- name: Security Compliance Playbook
  hosts: all
  become: yes  # Run tasks with sudo

  tasks:
    - name: Ensure the system is updated
      yum:
        name: '*'
        state: latest
      when: ansible_pkg_mgr == 'yum'  # Adjust for other package managers

    - name: Disable unused services
      service:
        name: "{{ item }}"
        enabled: no
        state: stopped
      loop:
        - telnet
        - ftp
      when: ansible_os_family == 'RedHat'  # Adjust for other operating systems

    - name: Set strong password policies
      pam_password:
        name: system-auth
        retry: 3
        minlen: 10
        ucredit: -1
        lcredit: -1
        dcredit: -1
        ocredit: -1

    - name: Configure SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: "{{ item.state | default('present') }}"
      loop:
        - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
      notify: Restart SSH service

  handlers:
    - name: Restart SSH service
      service:
        name: sshd
        state: restarted
